### ISSUE TITLE
Conflicts in svelte resolve

### ISSUE THREAD

**Issue by DanielAlcaraz** [romkor/svelte-portal#176]
Hi,

I upgraded my project dependencies and some new warnings appeared. This is the message:
`[vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.`

Here there is more info about the conflicts by the **vite-plugin-svelte** team:
[https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve)

**Comment by development-vargamarcel** [comment]
this might help (for maintaner): 
isue: https://github.com/ItalyPaleAle/svelte-spa-router/issues/310
fix: https://github.com/ItalyPaleAle/svelte-spa-router/pull/313

**Comment by jonnitto** [comment]
Should be solved with https://github.com/romkor/svelte-portal/commit/85fdeafa322f466752aa7d2adcb03d05c98310dc

**Comment by development-vargamarcel** [comment]
Thanks a ton

**Comment by ctibo** [comment]
I'm still getting the error with v2.2.1.
Rolling back to v2.2.0 removes the issue.

Relevant package.json info from my setup :
```
"@sveltejs/kit": "^1.20.4",
"svelte": "^4.2.7",
"svelte-preprocess": "^5.1.0",
"svelte-portal": "^2.2.1"
"typescript": "^5.0.0",
"vite": "^4.5.0"

``` 

The issue: 
```
OUTPUT:
#12 28.71 2:27:47 PM [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.
#12 28.71
#12 28.71 svelte-portal@2.2.1
#12 28.71
#12 28.71 Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.
[2024-Feb-28 14:27:48.181001]
```

**Comment by mig-hub** [comment]
Same, I get the error with 2.2.1
Indeed it does not warn when using 2.2.0 instead
